eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@127.0.0.1:1111/eureka/
  instance:
    prefer-ip-address: true
spring:
  redis:
    host: 127.0.0.1
    database: 1
  application:
    name: game-login
  datasource:
    username: root
    password: 123456
    driver-class-name:  com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/game-server?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    prefix: classpath:/page/ #添加前缀
    suffix: .html #添加后缀
    cache: false
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql
#  refresh: true
#  repository-locations:
#    - classpath:com/game/login/repository/xml/*Mapper.xml
server:
  port: 6002
  tomcat:
    uri-encoding: UTF-8

    
system:
  #客户端配置
  client:
    clients[0]:
      clientId: lvhaibao
      clientSecret: 123456
    clients[1]:
      clientId: lhb
      clientSecret: 123456
    clients[2]:
      clientId: app
      clientSecret: app
  social:
    qq:
      app-id: 101386962
      app-secret: 2a0f820407df400b84a854d054be8b6a
      providerId: callback.do

    filterProcessesUrl: /qqLogin
    weixin:
      app-id: wx8a47a66e22296c62
      app-secret: deb57af7ec1753a2668889e74b34b789