eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@127.0.0.1:1111/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 9400
spring:
  application:
    name: zipkin-server
  main:
    allow-bean-definition-overriding: true
management:
  metrics:
   web:
    server:
      auto-time-requests: false
  server:
    port: 9400  #指定监听端口，不指定则语server端口一直
  endpoints:  # 结束服务关闭
    web:
      exposure:
        include: info,shutdown
info:     #模块说明
  app.name: 游戏测试
  author.name: wx
  author.function: zipkin服务

