spring:
  application:
    name: game-auth
  datasource:
    username: root
    password: 123456
    driver-class-name:  com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/game-server?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
server:
  port: 6003
  tomcat:
    uri-encoding: UTF-8
